In [1]:
# Given this nest dictionary grab the word "hello"
d = {'k1':[1,2,3,{'tricky':['test','apple','inception',{'target':[1,2,3,'hello']}]}]}

In [10]:
hello = d['k1'][3]['tricky'][3]['target'][3]

print(hello)


hello


In [ ]:
# Task 1: Fix the issue in the following function so that the `modify()` function does NOT modify the global `x`.
#x = 10

#def modify():
   # x = x + 5  # Fix this
   # print(x)

#modify()
#print(x)  # Should still print 10

In [15]:
x = 10

def modify(x):
    x = x + 5
    print(x)
    return x

x_new = modify(x)
print(x)



15
10


In [ ]:
# Task 2:
# Create a function which takes as parameter a list, and a target value
# it returns the combination of two list numbers which sums to target value
# if list = [1,2,3] and target = 4, it should return (1,3)

In [16]:
def find_pair(lst, target):
    for i in range(len(lst)):
        for j in range(i + 1, len(lst)):
            if lst[i] + lst[j] == target:
                return (lst[i], lst[j])
    return None


print(find_pair([1, 2, 3], 4))


(1, 3)


In [ ]:
# Task:
# 1. Convert the string "2024-03-11 14:30:00" to a `datetime` object
# 2. Add 5 days, 3 hours, and 45 minutes
# 3. Extract and print only the day of the week

In [17]:
from datetime import datetime, timedelta

date_str = "2024-03-11 14:30:00"
dt = datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S")

delta = timedelta(days=5, hours=3, minutes=45)
new_dt = dt + delta

day_of_week = new_dt.strftime("%A")

print("Updated DateTime:", new_dt)
print("Day of the Week:", day_of_week)


Updated DateTime: 2024-03-16 18:15:00
Day of the Week: Saturday


In [ ]:
# Task:
# 1. Create a list of integers: [5, 15, 25, 35, 45]
# 2. Use the filter() function to remove numbers that are not divisible by 5.
# 3. Then, use map() to subtract 2 from each remaining number.
# 4. Convert the result back into a list and print it.


In [18]:
numbers = [5, 15, 25, 35, 45]
filtered_numbers = filter(lambda x: x % 5 == 0, numbers)
modified_numbers = map(lambda x: x - 2, filtered_numbers)
result = list(modified_numbers)
print(result)


[3, 13, 23, 33, 43]


In [20]:
# Task: Given the matrix below, extract:
# 1. Rows 4, 3, 1
# 2. Columns 4 and 2
# 3. The elements at positions (0,0), (1,2), (3,4).
# 4. All values greater than 5

#import numpy as np

#matrix = np.array([
 #   [1,  5,  9,  4],
  #  [7,  2,  8,  6],
   # [3,  8,  5,  9],
    #[6,  7,  2,  3],
    #[4,  9,  6,  1]
#])

In [22]:
import numpy as np

matrix = np.array([
    [1,  5,  9,  4],
    [7,  2,  8,  6],
    [3,  8,  5,  9],
    [6,  7,  2,  3],
    [4,  9,  6,  1]
])


rows_extracted = matrix[[3, 2, 0], :]
cols_extracted = matrix[:, [3, 1]]
elements = matrix[[0, 1, 3], [0, 2, 3]]
values_greater_than_5 = matrix[matrix > 5]

print("Extracted Rows:\n", rows_extracted)
print("\nExtracted Columns:\n", cols_extracted)
print("\nSpecific Elements:", elements)
print("\nValues Greater Than 5:", values_greater_than_5)


Extracted Rows:
 [[6 7 2 3]
 [3 8 5 9]
 [1 5 9 4]]

Extracted Columns:
 [[4 5]
 [6 2]
 [9 8]
 [3 7]
 [1 9]]

Specific Elements: [1 8 3]

Values Greater Than 5: [9 7 8 6 8 9 6 7 9 6]


In [ ]:
# Task: Create a 5x5 matrix filled with random integers between 10 and 50
# Subtract the row-wise mean from each row
# Divide all even numbers by 2 and multiply odd numbers by 3  hint: use np.where()
# p.s row-wise (mesatarja per rresht, tu iteru neper kolona axis=1)

In [27]:
np.random.seed(42)
matrix = np.random.randint(10, 51, (5, 5))

row_means = matrix.mean(axis=1, keepdims=True)
normalized_matrix = matrix - row_means
transformed_matrix = np.where(normalized_matrix % 2 == 0, normalized_matrix / 2, normalized_matrix * 3)


print("Original Matrix:\n", matrix)

print("\nRow-wise Mean Subtracted:\n", normalized_matrix)
print("\nFinal Transformed Matrix:\n", transformed_matrix)



Original Matrix:
 [[48 38 24 17 30]
 [48 28 32 20 20]
 [33 45 49 33 12]
 [31 11 33 39 47]
 [11 30 42 21 31]]

Row-wise Mean Subtracted:
 [[ 16.6   6.6  -7.4 -14.4  -1.4]
 [ 18.4  -1.6   2.4  -9.6  -9.6]
 [ -1.4  10.6  14.6  -1.4 -22.4]
 [ -1.2 -21.2   0.8   6.8  14.8]
 [-16.    3.   15.   -6.    4. ]]

Final Transformed Matrix:
 [[ 49.8  19.8 -22.2 -43.2  -4.2]
 [ 55.2  -4.8   7.2 -28.8 -28.8]
 [ -4.2  31.8  43.8  -4.2 -67.2]
 [ -3.6 -63.6   2.4  20.4  44.4]
 [ -8.    9.   45.   -3.    2. ]]


In [28]:
# Task:
# 1. Create an array: [3, np.nan, 7, 2, np.nan, 9]
# 2. Replace NaNs with the mean of non-NaN values
# 3. Count how many NaNs were in the array

#array = np.array([3, np.nan, 7, 2, np.nan, 9])


In [29]:
array = np.array([3, np.nan, 7, 2, np.nan, 9])

nan_mask = np.isnan(array)
mean_value = np.nanmean(array)
array[nan_mask] = mean_value

nan_count = np.sum(nan_mask)

print("Updated Array:", array)
print("Number of NaNs replaced:", nan_count)


Updated Array: [3.   5.25 7.   2.   5.25 9.  ]
Number of NaNs replaced: 2


In [ ]:
# Task: Replace all values above 30°C with "HOT", below 20°C with "COLD", otherwise "NORMAL"
#temps = np.array([25, 30, 33, 20, 18, 15, 29, 35])

In [30]:
temps = np.array([25, 30, 33, 20, 18, 15, 29, 35])

categorized_temps = np.where(temps > 30, "HOT", np.where(temps < 20, "COLD", "NORMAL"))

print(categorized_temps)


['NORMAL' 'NORMAL' 'HOT' 'NORMAL' 'COLD' 'COLD' 'NORMAL' 'HOT']


In [ ]:
# Task:
# Generate an array of 20 random numbers between 1 and 100
# Sort the array in descending order   (hint. [::-1] or np.flip())
# Find the index of the largest even number

In [39]:
arr = np.random.randint(1, 101, 20)

sorted_arr = np.sort(arr)[::-1]

largest_even_index = np.where(sorted_arr % 2 == 0)[0][0] if np.any(sorted_arr % 2 == 0) else None

print("Original Array:", arr)
print("Sorted Array:", sorted_arr)
print("Index of Largest Even Number:", largest_even_index)


Original Array: [92 89 62 97  1 27 62 77  3 70 72 27  9 62 37 97 51 44 24 79]
Sorted Array: [97 97 92 89 79 77 72 70 62 62 62 51 44 37 27 27 24  9  3  1]
Index of Largest Even Number: 2


In [ ]:
# Task: You have a dataset representing daily energy consumption (kWh) for 30 days:
# 1.Find dayswhere consumption is above the (mean + 1.5*std) (potential anomalies)
# 2.Replace those anomalies with the mean consumption
# 3.Normalize the data to range [0, 1]

#np.random.seed(42)
#energy_data = np.random.randint(200, 600, size=30)

# find mean and std


# Anomalies: above mean + 1.5 * std


# Replace with mean value


# Normalize the data to range [0, 1]


In [40]:
np.random.seed(42)
energy_data = np.random.randint(200, 600, size=30)
mean_consumption = np.mean(energy_data)
std_consumption = np.std(energy_data)
threshold = mean_consumption + 1.5 * std_consumption
anomalies = energy_data > threshold
energy_data_cleaned = np.where(anomalies, mean_consumption, energy_data)
normalized_data = (energy_data_cleaned - np.min(energy_data_cleaned)) / (np.max(energy_data_cleaned) - np.min(energy_data_cleaned))


print("Original Data:", energy_data)
print("Cleaned Data:", energy_data_cleaned)
print("Normalized Data:", normalized_data)


Original Data: [302 548 470 306 271 388 220 302 321 414 530 287 572 299 559 351 330 349
 508 457 543 493 585 391 476 360 513 221 452 435]
Cleaned Data: [302.         548.         470.         306.         271.
 388.         220.         302.         321.         414.
 530.         287.         408.43333333 299.         559.
 351.         330.         349.         508.         457.
 543.         493.         408.43333333 391.         476.
 360.         513.         221.         452.         435.        ]
Normalized Data: [0.24188791 0.96755162 0.73746313 0.25368732 0.15044248 0.49557522
 0.         0.24188791 0.2979351  0.57227139 0.91445428 0.19764012
 0.55585054 0.23303835 1.         0.38643068 0.32448378 0.38053097
 0.84955752 0.69911504 0.95280236 0.80530973 0.55585054 0.50442478
 0.75516224 0.41297935 0.86430678 0.00294985 0.68436578 0.63421829]
